# font_family JetBrains Nerd Font
font_family         Iosevka Nerd Font Mono
bold_font           auto
italic_font         auto
bold_italic_font    auto
font_size 16

disable ligatures no
enable_audio_bell no

shell             bash
shell_integration disabled

cursor_shape block

detect_urls  yes
url_color    #0087bd
url_style    curly

confirm_os_window_close 0

window_padding_width 20
cursor_blink_interval 0

remember_window_size no

cursor_blink_interval 0

background_opacity 1
hide_window_decorations yes

# Color palete
foreground              #eeeeee
background              #181818

cursor                  #f0d83c
cursor_text_color       #181818

selection_foreground    #181818
selection_background    #d8d8d8

# ANSI colors
color0  #181818
color1  #ab4642
color2  #8fba5f
color3  #f0d080
color4  #7cafc2
color5  #8f9f5f
color6  #86c1b9
color7  #eeeeee

color8  #585858
color9  #d0605a
color10 #a5c878
color11 #f5d995
color12 #8db5c5
color13 #82ad55
color14 #91cbc2
color15 #ffffff
