font_family JetBrainsMono Nerd Font
font_size 12

disable ligatures no
enable_audio_bell no

shell             bash
shell_integration disabled

cursor_shape block

url_style curly

# To close the terminal without confirmation
confirm_os_window_close 0

window_padding_width 20
cursor_blink_interval 0

remember_window_size no

dynamic_background_opacity yes

background            #1e1e1e
foreground            #d6d6d6
cursor                #e8e8e8
cursor_text_color     #0c0c0c
selection_background  #333333
selection_foreground  #e8e8e8

color0  #1a1a1a
color8  #5c5c5c
color1  #b86a6a
color9  #d08585
color2  #7ba368
color10 #96bd82
color3  #bda76a
color11 #d6be82
color4  #6889b8
color12 #82a3d0
color5  #9a7cb8
color13 #b496d0
color6  #68a5a5
color14 #82bebe
color7  #b0b0b0
color15 #d6d6d6